name: CI

on:
    push:
        branches: ["main" ]
    pull_request:
        branches: ["main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:  
            matrix:
                node-versions: [18.x, 20.x, 22.x]
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: use Node.js ${{ matrix.node-versions }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-versions }}
                cache: 'npm'
            
            - name: Install deps
              run: npm ci